
services:
  db:
    image: postgres:16
    container_name: taskapi-db
    environment:
      POSTGRES_DB: taskapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: taskapi-app
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/taskapi
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SECURITY_JWT_SECRET: CHANGE_ME_TO_A_LONG_RANDOM_SECRET
      SECURITY_JWT_EXPIRATION_MINUTES: 60
    ports:
      - "8080:8080"

volumes:
  postgres_data: