services:
  db:
    image: postgres:16
    container_name: taskapi-db
    environment:
      POSTGRES_DB: taskapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    restart: always
    build: .
    container_name: taskapi-app
    depends_on:
     db:
      condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SECURITY_JWT_SECRET: ${JWT_SECRET}
      SECURITY_JWT_EXPIRATION_MINUTES: 60
    ports:
      - "8080:8080"

volumes:
  postgres_data: