spring.application.name=taskapi

# swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

spring.data.web.pageable.max-page-size=100
spring.data.web.pageable.default-page-size=20

logging.level.com.example.taskapi=INFO

security.jwt.secret=CHANGE_ME_TO_LONG_RANDOM_SECRET_32CHARS_MIN
security.jwt.expiration-minutes=60

